### ISSUE TITLE
NVG causes error when unequiping/toggle on off

### ISSUE THREAD

**Issue by AZDrizzy** [ChuckTheSheep/Night-Vision-Chucked#2]
while night vision is engaged ill get an error if I try to unequip or toggle goggle up or down. NVG will still stay engaged even if I'm not wearing googles. Also power level changes nothing. Here's the stack trace for the error.

STACK TRACE
-----------------------------------------
function: onDeactivate -- file: eris_nvg.lua line # 119 | MOD: Night Vision Chucked
function: perform -- file: eris_nvg.lua line # 134 | MOD: Night Vision Chucked.
[29-03-23 19:36:54.158] ERROR: General     , 1680133014158> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: getDisplayName of non-table: null at KahluaThread.tableget line:1689..
[29-03-23 19:36:54.158] ERROR: General     , 1680133014158> DebugLogStream.printException> Stack trace:.
[29-03-23 19:36:54.161] LOG  : General     , 1680133014161> -----------------------------------------
STACK TRACE
-----------------------------------------
function: onDeactivate -- file: eris_nvg.lua line # 119 | MOD: Night Vision Chucked
function: perform -- file: eris_nvg.lua line # 134 | MOD: Night Vision Chucked.

**Comment by AZDrizzy** [comment]
Hey. I saw you closed this as completed. Went to test it and it works mostly, but maybe even better than before. The power output scaling still doesn't work, although night vision just works/looks better at night. Anyways I just wanted to say thank you for fixing this.

**Comment by Chuckleberry-Finn** [comment]
No problem, I honestly forgot you mentioned power scaling. I'll have to recheck whats going on there.

**Comment by AZDrizzy** [comment]
Well Thank you again 😺
